SSID='Enter Twilio SSID'
AUTH_TOKEN='Enter Twilio Authentication token'
FROM_NUMBER='+ Enter Twilio Alloted Number'
TO_NUMBER='+ Enter Your Number'
BOLT_API='Enter Bolt API key'
DEVICE_ID='Enter Bolt Device Id'
